name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Node
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        
    - name: Test
      run: |
        npm install
        npm run test-cloud

  Build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Node
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        
    - name: Build
      run: |
        npm install
        npm run build
